name: ci

on:
  workflow_dispatch:
    inputs:
      app-name:
        description: 'Name of the application to package'
        default: 'netwebapi'
        required: true
        type: string
      
env:
  LANGUAGE: 'csharp'
jobs:
  lint: 
    uses: dgeorgievski/my-github-actions/.github/workflows/lint-csharp.yml@v1
    with:
      language: ${ env.LANGUAGE }
      app-name: ${{ inputs.app-name }}
  test:
    needs: lint
    uses: dgeorgievski/my-github-actions/.github/workflows/test-csharp.yml@v1
    with:
      language: ${ env.LANGUAGE }
      app-name: ${{ inputs.app-name }}

  build:
    needs: test
    uses: dgeorgievski/my-github-actions/.github/workflows/build-csharp.yml@v1
    with:
      language: ${ env.LANGUAGE }
      app-name: ${{ inputs.app-name }}

