name: CI

on:
  workflow_dispatch:
    inputs:
      language:
        description: 'Programming language'
        required: true
        default: 'csharp'
        type: string
      app-name:
        description: 'Application name'
        default: 'netwebapi'
        required: true
        type: string

jobs:
  lint: 
    uses: dgeorgievski/my-github-actions/.github/workflows/lint-csharp.yml@v6
    with:
      language: ${{ inputs.language }}
      app-name: ${{ inputs.app-name }}
  test:
    needs: lint
    uses: dgeorgievski/my-github-actions/.github/workflows/test-csharp.yml@v16
    with:
      language: ${{ inputs.language }}
      app-name: ${{ inputs.app-name }}

  build:
    needs: test
    uses: dgeorgievski/my-github-actions/.github/workflows/build-csharp.yml@v10
    with:
      language: ${{ inputs.language }}
      app-name: ${{ inputs.app-name }}

  package:
    needs: build
    uses: dgeorgievski/my-github-actions/.github/workflows/package-csharp.yml@v11
    with:
      language: ${{ inputs.language }}
      app-name: ${{ inputs.app-name }}
      context: src/NetWebApi.API
      dockerFile: src/NetWebApi.API/Dockerfile
      imageTag: ${{ needs.build.outputs.app_version }}
      push: true

  security:
    needs: [build, package]
    uses: dgeorgievski/my-github-actions/.github/workflows/security-scan.yml@v14
    with:
      registry: ghcr.io
      image-name: dgeorgievski/${{ inputs.app-name }}
      image-tag: ${{ needs.build.outputs.app_version }}
      dockerfile: src/NetWebApi.API/Dockerfile

  deploy:
    needs: security
    uses: dgeorgievski/my-github-actions/.github/workflows/deploy-csharp-az-app-service.yml@v18
    with:
      azure_webapp_name: ${{ inputs.app-name }}
      azure_webapp_package_path: '.'
    