name: CI

on:
  workflow_dispatch:
    inputs:
      language:
        description: 'Programming language'
        required: true
        default: 'csharp'
        type: string
      app-name:
        description: 'Application name'
        default: 'netwebapi'
        required: true
        type: string

jobs:
  lint: 
    uses: dgeorgievski/my-github-actions/.github/workflows/lint-${{ inputs.language }}.yml@v4
    with:
      language: ${{ inputs.language }}
      app-name: ${{ inputs.app-name }}
  test:
    needs: lint
    uses: dgeorgievski/my-github-actions/.github/workflows/test-${{ inputs.language }}.yml@v4
    with:
      language: ${{ inputs.language }}
      app-name: ${{ inputs.app-name }}

  build:
    needs: test
    uses: dgeorgievski/my-github-actions/.github/workflows/build-${{ inputs.language }}.yml@v6
    with:
      language: ${{ inputs.language }}
      app-name: ${{ inputs.app-name }}

  package:
    needs: build
    uses: dgeorgievski/my-github-actions/.github/workflows/package-${{ inputs.language }}.yml@v6
    with:
      context: src/NetWebApi.API
      dockerFile: src/NetWebApi.API/Dockerfile
      language: ${{ inputs.language }}
      app-name: ${{ inputs.app-name }}
