name: Test Build Workflow

on:
  push:
    branches:
      - 'main'
      - 'feature/**'
      - 'fix/**'
    paths-ignore:
      - '.github/workflows/**'
      - 'README.md'
      - 'docs/**'
      - 'CHANGELOG.md'
      - 'LICENSE'
  pull_request:
    types:
      - opened
      - reopened
      - edited
    branches:
      - main
    
  workflow_dispatch:
    inputs:
      language:
        description: 'Programming language'
        required: true
        default: 'csharp'
        type: string
      app-name:
        description: 'Application name'
        default: 'netwebapi'
        required: true
        type: string
      dotnet-version:
        description: 'Dotnet version'
        required: false
        type: string
        default: '9.0.300'
      working-directory:
        description: 'Working directory for the .NET application. Default "."; can be set to a custom path.'
        required: false
        type: string
        default: 'src/NetWebApi.API'
      dotnet-tools-restore:
        description: 'Restore tools. If unchecked, install tools globally.'
        required: false
        type: boolean
        default: true
      dotnet-linter-csharpier:
        description: 'Lint with csharpier'
        required: false
        type: boolean
        default: true
      registry:
        description: 'Container registry'
        required: false
        type: string
        default: 'ghcr.io'
      docker-context:
        description: 'Context for Docker build. Default "."'
        required: false
        type: string
        default: 'src/NetWebApi.API'
      docker-file:
        description: 'Dockerfile path. Default ./Dockerfile; can be set to a custom Dockerfile path'
        required: false
        type: string
        default: 'src/NetWebApi.API/Dockerfile'

jobs:
  test:
    uses: dgeorgievski/my-github-actions/.github/workflows/csharp-build.yml@test-cs
    with:
      app-name: ${{ inputs.app-name || 'netwebapi'}} 
      language: ${{ inputs.language || 'csharp'}} 
      dotnet-version: ${{ inputs.dotnet-version || '9.0.300' }}
      dotnet-tools-restore: ${{ inputs.dotnet-tools-restore || true }}
      dotnet-linter-csharpier: true
      dotnet-linter-roslynator: false
      security-trivy: true
      security-snyk: false
      registry: ${{ inputs.registry || 'ghcr.io' }}
      docker-context: ${{ inputs.docker-context || 'src/NetWebApi.API' }}
      docker-file: ${{ inputs.docker-file || 'src/NetWebApi.API/Dockerfile' }}
    secrets: inherit
