name: Test Build Workflow

on:
  workflow_dispatch:
    inputs:
      language:
        description: 'Programming language'
        required: true
        default: 'csharp'
        type: string
      app-name:
        description: 'Application name'
        default: 'netwebapi'
        required: true
        type: string
      dotnet-version:
        description: 'Dotnet version'
        required: false
        type: string
        default: '9.0.300'
      dotnet-tools-restore:
        description: 'Restore tools. If unchecked, install tools globally.'
        required: false
        type: boolean
        default: true
      dotnet-linter-csharpier:
        description: 'Lint with csharpier'
        required: false
        type: boolean
        default: true
      dotnet-linter-roslynator:
        description: 'Lint with roslynator'
        required: false
        type: boolean
        default: false
      registry:
        description: 'Container registry'
        required: false
        type: string
        default: 'ghcr.io'
jobs:
  test:
    uses: dgeorgievski/my-github-actions/.github/workflows/csharp-build.yml@ddh-85
    with:
      app-name: ${{ inputs.app-name }}
      language: ${{ inputs.language }}
      dotnet-version: ${{ inputs.dotnet-version }}
      dotnet-tools-restore: ${{ inputs.dotnet-tools-restore }}
      dotnet-linter-csharpier: true
      dotnet-linter-roslynator: false
      security-trivy: true
      security-snyk: false
      registry: ${{ inputs.registry }}
      docker-context: 'src/NetWebApi.API'
      docker-file: 'src/NetWebApi.API/Dockerfile'
    secrets: inherit
