name: Test Composite Actions

on:
  workflow_dispatch:
    inputs:
      language:
        description: 'Programming language'
        required: true
        default: 'csharp'
        type: string
      app-name:
        description: 'Application name'
        default: 'netwebapi'
        required: true
        type: string
      dotnet-version:
        description: 'Dotnet version'
        required: false
        type: string
        default: '9.0.300'
      dotnet-tools-restore:
        description: 'Restore project package, or install it globbally.'
        required: false
        type: boolean
        default: true
      dotnet-linter:
        description: 'Dotnet linter to use. csharpier | roslynator'
        required: false
        type: choice
        options:
          - csharpier
          - roslynator
        default: 'csharpier'
    
    
jobs:
  test:
    uses: dgeorgievski/my-github-actions/.github/workflows/dev-csharp.yaml@composites
    with:
      app-name: ${{ inputs.app-name }}
      language: ${{ inputs.language }}
      dotnet-version: ${{ inputs.dotnet-version }}
      dotnet-tools-restore: ${{ inputs.dotnet-tools-restore }}
      dotnet-linter: ${{ inputs.dotnet-linter }}
